MVC_test/MVC_test/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_test.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

MVC_test/MVC_test/Models/withdrawCash.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_test.Models
{
    public class withdrawCash
    {
        public int amountToWithdraw { get; set; }
    }
}

MVC_test/MVC_test/Controllers/ATMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_test.Models;

namespace MVC_test.Controllers
{
    public class ATMController : Controller
    {
        // GET: ATM
        public ActionResult Index()
        {
            ViewBag.Balance = 0;
            return View();
        }
        
        public ActionResult Withdraw()
        {
            ViewBag.Balance = 0;
            ViewBag.showBalance = false;

            withdrawCash cash = new withdrawCash();
            
            return View();
        }
        public ActionResult Deposit()
        {
            ViewBag.Balance = 0;
            ViewBag.showBalance = false;
            return View();
        }
        [HttpPost]
        public ActionResult Deposit(FormCollection frm)
        {
            ViewBag.showBalance = true;
            ViewBag.TakeOutRequest = frm["deposit"];
            return View();
        }
        [HttpPost]
        public ActionResult Withdraw(FormCollection frm)
        {
            ViewBag.Balance = 0;
            ViewBag.showBalance = true;
            ViewBag.TakeOutRequest = frm["withdraw"];

            return View();
        }
    }
}

MVC_test/MVC_test/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_test.Controllers
{
    public class HomeController : Controller
    {
        bool flag = false;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Test()
        {
            ViewBag.flagvalue = flag;
            ViewBag.Message = "This is a test page";
            
            return View();

        }
        [HttpPost]
        public ActionResult Test(FormCollection frm)
        {
            flag = true;
            ViewBag.flagvalue = flag;
            ViewBag.First = frm["firstName"].ToString();
            ViewBag.Last = frm["lastName"].ToString();
            ViewBag.Responce = frm["Responce"].ToString();
            ViewBag.Ice = frm["iceRadio"].ToString();

            return View();

        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult ATM()
        {
            return View();
        }
            
    }
}

MVC_test/MVC_test/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MVC_test.Controllers
{
    public class MoviesController : Controller
    {
        // GET: Movies
        public ActionResult Random()
        {
            return View();
        }
    }
}

MVC_test/MVC_test/Views/ATM/Deposit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Deposit Money</title>
    <meta name="viewport" content="width=device-width" />
    <title>Withdraw</title>
</head>
<body>
    @using (Html.BeginForm("Deposit", "ATM", FormMethod.Post))
    {
        <h1>DEPOSIT MONEY</h1>
        <p>Choose an amount to Deposit</p>
        <input type="number" name="deposit" placeholder="$$$" />
        <input type="submit" name="Submit Request" />

    }
    @if (@ViewBag.showBalance)
    {
        <p>You just deposited $ @ViewBag.takeOutRequest into your account</p>

    }

    <div>
        Deposit Page @Html.ActionLink("Withdraw", "Withdraw", "ATM")
    </div>
    <div>
        Home Page @Html.ActionLink("ATM", "ATM", "Home")
    </div>

</body>
</html>

MVC_test/MVC_test/Views/ATM/Withdraw.cshtml
@model MVC_test.Models.withdrawCash

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Withdraw Money</title>
    <meta name="viewport" content="width=device-width" />
    <title>Withdraw</title>
</head>
<body>
    @using (Html.BeginForm("Withdraw", "ATM", FormMethod.Post))
    {
        <h1>WITHDRAW MONEY</h1>
        <p>Choose an amount to Withdraw</p>
        <input type="number" name="withdraw" placeholder="$$$" />
        <input type="submit" name="Submit Request" />

    }
    @if (@ViewBag.showBalance)
    {
        <p>You just removed $ @ViewBag.takeOutRequest from your account</p>
       
    }
    <div>
        Deposit Page @Html.ActionLink("Deposit", "Deposit", "ATM")
    </div>
    <div>
        Home Page @Html.ActionLink("ATM", "ATM", "Home")
    </div>

</body>
</html>

MVC_test/MVC_test/Views/Home/ATM.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>Welcome to the ATM!</head>
<body>
    <div>
        <p>Choose an option</p>
        <table>
            <tr>
                <td>
                    Withdraw Money
                </td>
                <td>
                    @Html.ActionLink("Withdraw", "Withdraw", "ATM")
                </td>
            </tr>
            <tr>
                <td>
                    Deposit Money
                </td>
                <td>@Html.ActionLink("Deposit", "Deposit", "ATM")</td>
                
            </tr>
        </table>

    </div>

</body>

@Html.ActionLink("Home", "Index", "Home")



</html>

MVC_test/MVC_test/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_test/MVC_test/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_test/MVC_test/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_test/MVC_test/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div> 
        This is the login page
    </div>
</body>
</html>

MVC_test/MVC_test/Views/Home/Test.cshtml
@{
    Layout = null;
    List<SelectListItem> list = new List<SelectListItem>();
    list.Add(new SelectListItem() { Text = "Yes", Value = "Yes" });
    list.Add(new SelectListItem() { Text = "No", Value = "No" });
}

<!DOCTYPE html>

<html>

<title> Test Input MVC </title>
<meta name="viewport" content="width=device-width" />
<link href="~/Content/style.css" rel="stylesheet" />
 
<body>
    <div class="inputbox">
        @using (Html.BeginForm("Test", "Home", FormMethod.Post))
        {
            <h1>Test Input MVC</h1>
            <p>First Name:</p>
            <input type="text" name="firstName" id="usrid" value="" placeholder="Enter First Name"/>
            <p>Last Name:</p>
            <input type="text" name="lastName" id="usrid" value="" placeholder="Enter Last Name"/>
       
            <p>
                Responce @Html.DropDownList("Responce", list, "select")

            </p>
            <p>Preferred Type of Ice:</p>
            <p>cubed</p>
            <input type="radio" name="iceRadio" value="cubed"/>
            <p>crushed</p>
            <input type="radio" name="iceRadio" value="crushed"/>
            <p> <input type="submit" name="Submit" /></p>
            <p>
                @Html.ActionLink("Home", "Index")
            </p>
        }
        @if (@ViewBag.flagvalue)
        {
            <p>Your name is @ViewBag.First</p>
            <p>You prefer your ice @ViewBag.Ice</p>

        }

    </div>
</body>
</html>

MVC_test/MVC_test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Test", "Test", "Home")</li>
                    <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    <li>@Html.ActionLink("ATM", "ATM", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>